# A workflow that tests this action

name: SARIF comment workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Run the SARIF PR commenter

    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: false
          egress-policy: audit
          disable-telemetry: false
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            registry.npmjs.org:443
            registry-1.docker.io:443
            pipelinesghubeus6.actions.githubusercontent.com:443

      - name: "Checkout code"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          persist-credentials: false

      - name: Set npm cache path to user writable area
        run: |
          rm -rf ${{ github.workspace }}/.npm-2 || true
          mkdir -p ${{ github.workspace }}/.npm-2 || true
          npm cache clean -f
#          chown -R 1000:1000 ${{ github.workspace }}/.npm-2
#          npm config set cache ${{ github.workspace }}/.npm --global

      - name: Run npm in Docker
        run: |
          docker run --rm -v "$PWD":/workspace -w /workspace node:22 bash -c "npm config set cache /workspace/.npm-2"

      - name: Post SARIF findings in the pull request
        if: github.event_name == 'pull_request'
        uses: sett-and-hive/sarif-to-comment-action@main # This is a test, we want to dogfood main
        with:
            token:      ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            branch:     ${{ github.head_ref }}
            pr-number:  ${{ github.event.number }}
            sarif-file: "./test/fixtures/odc.sarif"
            title:      "Test comment with security scanning results"
            dry-run:    'false'
            odc-sarif: true
        env:
          CI: true
          npm_config_cache: ${{ github.workspace }}/.npm-2
